import Head from 'next/head'
import Link from 'next/link'
import Login from './login/Login'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Login Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>real Home /</h1>
      <Login />
    </div>
  )
}
