import Head from 'next/head'
import Link from 'next/link'
import Login from './login/Login'
import { useState } from 'react'
import MyApp from '../utils/MyApp'


export default function Home() {

  return (
    <div>
      <Head>
        <title>Login Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Login />
    </div>
  )
}
